Repository ufs-community/ufs-weather-model, pull requests merged in 2020-12, with the labels that each got.

#340 Release/public-v2: V2 doc updates
  doc/UsersGuide/source/FAQ.rst
  doc/UsersGuide/source/InputsOutputs.rst
  doc/UsersGuide/source/Introduction.rst
  doc/UsersGuide/source/SDFandNamelistExamplePractices.rst
  doc/UsersGuide/source/_static/fv3IO.png
  doc/UsersGuide/source/conf.py
Labels: documentation, release/public-v2

#333 Replace old regional SDF with FV3_GFS_v15_thompson_mynn
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss_cray.log
  tests/RegressionTests_wcoss_dell_p3.log
  tests/parm/ccpp_regional.nml.IN
  tests/rt.conf
  tests/rt.sh
  tests/tests/fv3_ccpp_regional_control
  tests/tests/fv3_ccpp_regional_quilt
  tests/tests/fv3_ccpp_regional_quilt_netcdf_parallel
  tests/tests/fv3_ccpp_regional_restart
Labels: Baseline Change, Ready for Review

#342 Add checkpoint restarts for ufs-cpld
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_gaea.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss_cray.log
  tests/RegressionTests_wcoss_dell_p3.log
  tests/default_vars.sh
  tests/fv3_conf/ccpp_control_run.IN
  tests/fv3_conf/ccpp_csawmg_run.IN
  tests/fv3_conf/ccpp_gfdlmp_run.IN
  tests/fv3_conf/ccpp_satmedmf_run.IN
  tests/fv3_conf/cpld_bmark_run.IN
  tests/fv3_conf/cpld_control_run.IN
  tests/fv3_conf/csawmg3shoc127_run.IN
  tests/fv3_conf/csawmg_run.IN
  tests/fv3_conf/csawmgshoc_run.IN
  tests/fv3_conf/fv3_run.IN
  tests/fv3_conf/gfdlmp_run.IN
  tests/fv3_conf/satmedmf_run.IN
  tests/fv3_conf/thompson_run.IN
  tests/fv3_conf/wsm6_run.IN
  tests/rt.conf
  tests/tests/cpld_bmark
  tests/tests/cpld_bmark_35d
  tests/tests/cpld_bmark_wave
  tests/tests/cpld_bmark_wave_35d
  tests/tests/cpld_control
  tests/tests/cpld_control_12h
  tests/tests/cpld_control_c192
  tests/tests/cpld_control_c384
  tests/tests/cpld_controlfrac_c384
  tests/tests/cpld_restart
  tests/tests/cpld_restart_bmark
  tests/tests/cpld_restart_c192
  tests/tests/cpld_restart_mx025
Labels: No Baseline Change, Ready for Commit, Ready for Review
