Repository ufs-community/ufs-weather-model, pull requests merged in 2023-01, with the labels that each got.

#1552 clean up gitaction yml
  .github/workflows/aux.yml
  .github/workflows/build_test.yml
  .github/workflows/save/aux._yml
  .github/workflows/save/build_test._yml
Labels: No Baseline Change

#1554 Faster, safer, compilation options targeted for HAFS operational upgrade
  HYCOM-interface/CMakeLists.txt
  cmake/Intel.cmake
  cmake/configure_gaea.intel.cmake
  tests/RegressionTests_acorn.intel.log
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_gaea.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss2.intel.log
  tests/rt.conf
  tests/rt.sh
  tests/run_test.sh
Labels: Ready for Commit Queue

#1563 Compile CICE with safe CPU instructions
  CICE-interface/CMakeLists.txt
  tests/RegressionTests_acorn.intel.log
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_gaea.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss2.intel.log
  tests/rt.sh
Labels: Baseline Change, Ready for Commit Queue

#1580 Platform-594 AutoRT Jenkins
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_gaea.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/auto-jenkins/jobs/bl.py
  tests/auto-jenkins/jobs/rt.py
  tests/auto-jenkins/rt_auto_jenkins.py
  tests/auto-jenkins/start_rt_auto_jenkins.sh
Labels: No Baseline Change, Ready for Review, Ready for Commit Queue
