Repository ufs-community/ufs-weather-model, pull requests merged in 2023-04, with the labels that each got.

#1681 Remove requirement for esmf and mapl debug versions, remove DEBUG_LINKMPI
  CMakeLists.txt
  cmake/Intel.cmake
  cmake/configure_acorn.cmake
  cmake/configure_cheyenne.intel.cmake
  cmake/configure_gaea.intel.cmake
  cmake/configure_macosx.intel.cmake
  cmake/configure_wcoss2.cmake
  doc/UsersGuide/source/ConfigParameters.rst
  modulefiles/ufs_acorn.intel_debug.lua
  modulefiles/ufs_cheyenne.gnu_debug.lua
  modulefiles/ufs_cheyenne.intel_debug.lua
  modulefiles/ufs_common_debug.lua
  modulefiles/ufs_expanse.intel_debug
  modulefiles/ufs_gaea.intel_debug.lua
  modulefiles/ufs_hera.gnu_debug.lua
  modulefiles/ufs_hera.intel_debug.lua
  modulefiles/ufs_jet.intel_debug.lua
  modulefiles/ufs_linux.gnu_debug
  modulefiles/ufs_macosx.gnu_debug
  modulefiles/ufs_macosx.intel_debug
  modulefiles/ufs_orion.intel_debug.lua
  modulefiles/ufs_s4.intel_debug.lua
  modulefiles/ufs_wcoss2.intel_debug.lua
  tests/RegressionTests_acorn.intel.log
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_gaea.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss2.intel.log
  tests/compile.sh
  tests/fv3_conf/compile_qsub.IN_wcoss2
Labels: No Baseline Change, Ready for Commit Queue, jet-intel-RT, jenkins-ci

#1407 add cmeps capable atm-wav test
  CMakeLists.txt
  cmake/configure_apps.cmake
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_gaea.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss2.intel.log
  tests/default_vars.sh
  tests/fv3_conf/control_run.IN
  tests/fv3_conf/cpld_control_run.IN
  tests/fv3_conf/hafs_ww3_run.IN
  tests/parm/nems.configure.atmw.IN
  tests/parm/ww3_points.list
  tests/parm/ww3_shel.nml.IN
  tests/rt.conf
  tests/rt.sh
  tests/run_test.sh
  tests/tests/atmwav_control_noaero_p8
  tests/tests/control_atmwav
  tests/tests/cpld_bmark_p8
  tests/tests/cpld_bmark_p8_35d
  tests/tests/cpld_control_c192_p8
  tests/tests/cpld_restart_bmark_p8
  tests/tests/cpld_restart_c192_p8
  tests/tests/cpld_restart_p8
  tests/tests/cpld_restart_qr_p8
  tests/tests/hafs_regional_atm_ocn_wav
  tests/tests/hafs_regional_atm_wav
  tests/tests/hafs_regional_storm_following_1nest_atm_ocn_wav
Labels: Baseline Change, Ready for Review, Ready for Commit Queue, jenkins-ci

#1712 [production/AQM.v7] Update WCOSS2 Intel lua for production available packages/libraries.
  modulefiles/ufs_wcoss2.intel.lua
  tests/RegressionTests_wcoss2.intel.log
Labels: No Baseline Change, Ready for Commit Queue, Priority: High

#1690 Update in-line post for RRFS and GFS
  tests/RegressionTests_cheyenne.gnu.log
  tests/RegressionTests_cheyenne.intel.log
  tests/RegressionTests_hera.gnu.log
  tests/RegressionTests_hera.intel.log
  tests/RegressionTests_jet.intel.log
  tests/RegressionTests_orion.intel.log
  tests/RegressionTests_wcoss2.intel.log
  tests/fv3_conf/control_run.IN
  tests/fv3_conf/cpld_control_run.IN
  tests/parm/post_itag
  tests/parm/post_itag_gfs
  tests/parm/postxconfig-NT-gfs.txt
  tests/parm/postxconfig-NT-gfs_FH00.txt
  tests/rt.sh
Labels: Baseline Change, Ready for Commit Queue, jenkins-ci
